apiVersion: v1
kind: ConfigMap
metadata:
  namespace: metallb
  name: config
data:
  config: |
    address-pools:
    - name: default
      protocol: layer2
      addresses:
       - 192.168.0.250-192.168.0.250
